# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate mpsc_requests

Name:           rust-mpsc_requests
Version:        0.3.3
Release:        %autorelease
Summary:        Mpsc channels but with a response

License:        MPL-2.0
URL:            https://crates.io/crates/mpsc_requests
Source0:        %{crates_source}
Source1:        LICENSE-MPL-2.0

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Mpsc channels but with a response.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MPL-2.0
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dm 0644 %{SOURCE1} -t %{buildroot}%{crate_instdir}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
