# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate fern

Name:           rust-fern
Version:        0.6.2
Release:        %autorelease
Summary:        Simple, efficient logging

License:        MIT
URL:            https://crates.io/crates/fern
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop example-only dependency on clap ^2
Patch:          fern-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Simple, efficient logging.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+colored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+colored-devel %{_description}

This package contains library source intended for building other packages which
use the "colored" feature of the "%{crate}" crate.

%files       -n %{name}+colored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+date-based-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+date-based-devel %{_description}

This package contains library source intended for building other packages which
use the "date-based" feature of the "%{crate}" crate.

%files       -n %{name}+date-based-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libc-devel %{_description}

This package contains library source intended for building other packages which
use the "libc" feature of the "%{crate}" crate.

%files       -n %{name}+libc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+meta-logging-in-format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+meta-logging-in-format-devel %{_description}

This package contains library source intended for building other packages which
use the "meta-logging-in-format" feature of the "%{crate}" crate.

%files       -n %{name}+meta-logging-in-format-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# drop one example program that pulls in clap ^2
rm examples/cmd-program.rs

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
