# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate buf_redux

Name:           rust-buf_redux
Version:        0.8.4
Release:        %autorelease
Summary:        Drop-in replacements for buffered I/O in std::io with extra features

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/buf_redux
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Drop-in replacements for buffered I/O in `std::io` with extra features.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+slice-deque-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+slice-deque-devel %{_description}

This package contains library source intended for building other packages which
use the "slice-deque" feature of the "%{crate}" crate.

%files       -n %{name}+slice-deque-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
