# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate jemalloc-sys
%global upstream_version 0.5.4+5.3.0-patched

# compile and run tests only on supported architectures
%global supported_arches x86_64 aarch64 ppc64le

Name:           rust-jemalloc-sys
Version:        0.5.4
Release:        %autorelease
Summary:        Rust FFI bindings to jemalloc

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/jemalloc-sys
Source:         %{crates_source %{crate} %{upstream_version}}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          jemalloc-sys-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust FFI bindings to jemalloc.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/jemalloc/COPYING
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/update_jemalloc.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+background_threads-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+background_threads-devel %{_description}

This package contains library source intended for building other packages which
use the "background_threads" feature of the "%{crate}" crate.

%files       -n %{name}+background_threads-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+background_threads_runtime_support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+background_threads_runtime_support-devel %{_description}

This package contains library source intended for building other packages which
use the "background_threads_runtime_support" feature of the "%{crate}" crate.

%files       -n %{name}+background_threads_runtime_support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disable_cache_oblivious-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disable_cache_oblivious-devel %{_description}

This package contains library source intended for building other packages which
use the "disable_cache_oblivious" feature of the "%{crate}" crate.

%files       -n %{name}+disable_cache_oblivious-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disable_initial_exec_tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disable_initial_exec_tls-devel %{_description}

This package contains library source intended for building other packages which
use the "disable_initial_exec_tls" feature of the "%{crate}" crate.

%files       -n %{name}+disable_initial_exec_tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+profiling-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+profiling-devel %{_description}

This package contains library source intended for building other packages which
use the "profiling" feature of the "%{crate}" crate.

%files       -n %{name}+profiling-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stats-devel %{_description}

This package contains library source intended for building other packages which
use the "stats" feature of the "%{crate}" crate.

%files       -n %{name}+stats-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unprefixed_malloc_on_supported_platforms-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unprefixed_malloc_on_supported_platforms-devel %{_description}

This package contains library source intended for building other packages which
use the "unprefixed_malloc_on_supported_platforms" feature of the "%{crate}" crate.

%files       -n %{name}+unprefixed_malloc_on_supported_platforms-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{upstream_version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%ifarch %{supported_arches}
%cargo_build
%endif

%install
%cargo_install

%if %{with check}
%ifarch %{supported_arches}
%check
%cargo_test
%endif
%endif

%changelog
%autochangelog
