# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate devise_core

Name:           rust-%{crate}
Version:        0.4.1
Release:        %autorelease
Summary:        Library for devising derives and other procedural macros

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/%{crate}
Source0:        %{crates_source}
Source1:        LICENSE-APACHE
Source2:        LICENSE-MIT

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for devising derives and other procedural macros}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dm 0644 %{SOURCE1} -t %{buildroot}%{crate_instdir}
install -Dm 0644 %{SOURCE2} -t %{buildroot}%{crate_instdir}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
