# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate rocket

Name:           rust-rocket
Version:        0.5.0
Release:        %autorelease
Summary:        Web framework with a focus on usability, security, extensibility, and speed

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rocket
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/rwf2/Rocket/master/LICENSE-APACHE
Source2:        https://raw.githubusercontent.com/rwf2/Rocket/master/LICENSE-MIT

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Web framework with a focus on usability, security, extensibility, and
speed.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http2-devel %{_description}

This package contains library source intended for building other packages which
use the "http2" feature of the "%{crate}" crate.

%files       -n %{name}+http2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+msgpack-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+msgpack-devel %{_description}

This package contains library source intended for building other packages which
use the "msgpack" feature of the "%{crate}" crate.

%files       -n %{name}+msgpack-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rmp-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rmp-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "rmp-serde" feature of the "%{crate}" crate.

%files       -n %{name}+rmp-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+secrets-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+secrets-devel %{_description}

This package contains library source intended for building other packages which
use the "secrets" feature of the "%{crate}" crate.

%files       -n %{name}+secrets-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid_-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid_-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid_" feature of the "%{crate}" crate.

%files       -n %{name}+uuid_-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dm 0644 %{SOURCE1} -t %{buildroot}%{crate_instdir}
install -Dm 0644 %{SOURCE2} -t %{buildroot}%{crate_instdir}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
