# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate rocket_http

Name:           rust-rocket_http
Version:        0.5.0
Release:        %autorelease
Summary:        Types, traits, and parsers for HTTP requests, responses, and headers

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rocket_http
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/rwf2/Rocket/master/LICENSE-APACHE
Source2:        https://raw.githubusercontent.com/rwf2/Rocket/master/LICENSE-MIT

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Types, traits, and parsers for HTTP requests, responses, and headers}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http2-devel %{_description}

This package contains library source intended for building other packages which
use the "http2" feature of the "%{crate}" crate.

%files       -n %{name}+http2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+private-cookies-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+private-cookies-devel %{_description}

This package contains library source intended for building other packages which
use the "private-cookies" feature of the "%{crate}" crate.

%files       -n %{name}+private-cookies-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-pemfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-pemfile-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-pemfile" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-pemfile-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_" feature of the "%{crate}" crate.

%files       -n %{name}+serde_-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid_-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid_-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid_" feature of the "%{crate}" crate.

%files       -n %{name}+uuid_-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f tls,serde,http2,private-cookies,serde,uuid

%build
%cargo_build

%install
%cargo_install
install -Dm 0644 %{SOURCE1} -t %{buildroot}%{crate_instdir}
install -Dm 0644 %{SOURCE2} -t %{buildroot}%{crate_instdir}

%if %{with check}
%check
# * couldn't read sa_sha256_key.pem: No such file or directory
# * skip tls as it refers to non-existing /../../examples/tls/private/
%cargo_test -- -- --skip 'src/header/accept.rs' --skip 'src/header/content_type.rs' --skip 'src/header/header.rs' --skip 'src/header/media_type.rs' --skip 'src/method.rs' --skip 'src/parse/uri/error.rs' --skip 'src/raw_str.rs' --skip 'src/status.rs' --skip 'src/uri/absolute.rs' --skip 'src/uri/asterisk.rs' --skip 'src/uri/authority.rs' --skip 'src/uri/fmt/formatter.rs' --skip 'src/uri/fmt/from_uri_param.rs' --skip 'src/uri/fmt/uri_display.rs' --skip 'src/uri/host.rs' --skip 'src/uri/origin.rs' --skip 'src/uri/path_query.rs' --skip 'src/uri/reference.rs' --skip 'src/uri/segments.rs' --skip 'src/uri/uri.rs'
%endif

%changelog
%autochangelog
