# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate stable-pattern

Name:           rust-stable-pattern
Version:        0.1.0
Release:        %autorelease
Summary:        Stable port of std::str::Pattern and friends

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/stable-pattern
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/SergioBenitez/stable-pattern/master/LICENSE-APACHE
Source2:        https://raw.githubusercontent.com/SergioBenitez/stable-pattern/master/LICENSE-MIT

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Stable port of std::str::Pattern and friends.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dm 0644 %{SOURCE1} -t %{buildroot}%{crate_instdir}
install -Dm 0644 %{SOURCE2} -t %{buildroot}%{crate_instdir}

%if %{with check}
%check
# * no method named `as_str` found for struct `std::str::RSplit
%cargo_test -- -- --skip 'src/split.rs'
%endif

%changelog
%autochangelog
