# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate multipart

Name:           rust-multipart
Version:        0.18.0
Release:        %autorelease
Summary:        Extension for HTTP libraries that provides support for POST requests

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/multipart
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A backend-agnostic extension for HTTP libraries that provides support
for POST multipart/form-data requests on both client and server.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%doc lorem_ipsum.txt

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/lorem_ipsum.txt
%{crate_instdir}/

%package     -n %{name}+buf_redux-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+buf_redux-devel %{_description}

This package contains library source intended for building other packages which
use the "buf_redux" feature of the "%{crate}" crate.

%files       -n %{name}+buf_redux-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+client-devel %{_description}

This package contains library source intended for building other packages which
use the "client" feature of the "%{crate}" crate.

%files       -n %{name}+client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+httparse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+httparse-devel %{_description}

This package contains library source intended for building other packages which
use the "httparse" feature of the "%{crate}" crate.

%files       -n %{name}+httparse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages which
use the "lazy_static" feature of the "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+quick-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quick-error-devel %{_description}

This package contains library source intended for building other packages which
use the "quick-error" feature of the "%{crate}" crate.

%files       -n %{name}+quick-error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+safemem-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+safemem-devel %{_description}

This package contains library source intended for building other packages which
use the "safemem" feature of the "%{crate}" crate.

%files       -n %{name}+safemem-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+server-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+server-devel %{_description}

This package contains library source intended for building other packages which
use the "server" feature of the "%{crate}" crate.

%files       -n %{name}+server-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tiny_http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tiny_http-devel %{_description}

This package contains library source intended for building other packages which
use the "tiny_http" feature of the "%{crate}" crate.

%files       -n %{name}+tiny_http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+twoway-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+twoway-devel %{_description}

This package contains library source intended for building other packages which
use the "twoway" feature of the "%{crate}" crate.

%files       -n %{name}+twoway-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
sed -ri '/dependencies.hyper/,+3d' Cargo.toml
sed -ri '/dependencies.iron/,+2d' Cargo.toml
sed -ri '/dependencies.nickel/,+2d' Cargo.toml
sed -ri '/^[[:blank:]]*default\b/d' Cargo.toml
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
