# Generated by rust2rpm 26
# * jemallocator/default dependency is needed
%bcond_with check
%global debug_package %{nil}

%global crate jemalloc-ctl

# compile and run tests only on supported architectures
%global supported_arches x86_64 aarch64 ppc64le

Name:           rust-jemalloc-ctl
Version:        0.5.4
Release:        %autorelease
Summary:        Safe wrapper over jemalloc's control and introspection APIs

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/jemalloc-ctl
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A safe wrapper over jemalloc's control and introspection APIs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disable_initial_exec_tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disable_initial_exec_tls-devel %{_description}

This package contains library source intended for building other packages which
use the "disable_initial_exec_tls" feature of the "%{crate}" crate.

%files       -n %{name}+disable_initial_exec_tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_std-devel %{_description}

This package contains library source intended for building other packages which
use the "use_std" feature of the "%{crate}" crate.

%files       -n %{name}+use_std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%ifarch %{supported_arches}
%cargo_build
%endif

%install
%cargo_install

%if %{with check}
%ifarch %{supported_arches}
%check
%cargo_test
%endif
%endif

%changelog
%autochangelog
