# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate plex

Name:           rust-plex
Version:        0.3.0
Release:        %autorelease
Summary:        Syntax extension for writing lexers and parsers

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/plex
Source:         %{crates_source}
Patch0:         plex-bump-redfa-version.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A syntax extension for writing lexers and parsers.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lalr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lalr-devel %{_description}

This package contains library source intended for building other packages which
use the "lalr" feature of the "%{crate}" crate.

%files       -n %{name}+lalr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lexer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lexer-devel %{_description}

This package contains library source intended for building other packages which
use the "lexer" feature of the "%{crate}" crate.

%files       -n %{name}+lexer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parser-devel %{_description}

This package contains library source intended for building other packages which
use the "parser" feature of the "%{crate}" crate.

%files       -n %{name}+parser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+redfa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+redfa-devel %{_description}

This package contains library source intended for building other packages which
use the "redfa" feature of the "%{crate}" crate.

%files       -n %{name}+redfa-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
